"""Stable machine-readable error codes.

These are part of the public API contract: clients switch on them. Add codes
freely; never rename or reuse one.
"""

UNAUTHORIZED = "UNAUTHORIZED"
FORBIDDEN = "FORBIDDEN"
NOT_FOUND = "NOT_FOUND"
CONFLICT = "CONFLICT"
RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
VALIDATION_ERROR = "VALIDATION_ERROR"
DATABASE_ERROR = "DATABASE_ERROR"
DATABASE_CONNECTION_ERROR = "DATABASE_CONNECTION_ERROR"
DATABASE_OPERATION_ERROR = "DATABASE_OPERATION_ERROR"
DATABASE_RESULT_ERROR = "DATABASE_RESULT_ERROR"
EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
INTERNAL_ERROR = "INTERNAL_ERROR"
HTTP_ERROR = "HTTP_ERROR"

# Auth (M3, BFF)
AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
INVALID_SESSION = "INVALID_SESSION"
SESSION_EXPIRED = "SESSION_EXPIRED"
TOKEN_VERIFICATION_FAILED = "TOKEN_VERIFICATION_FAILED"
CSRF_VALIDATION_FAILED = "CSRF_VALIDATION_FAILED"
OAUTH_EXCHANGE_FAILED = "OAUTH_EXCHANGE_FAILED"
IDENTITY_MAPPING_FAILED = "IDENTITY_MAPPING_FAILED"
